name: project_environment
channels:
  - conda-forge
dependencies:
  - python=3.6.8
  - pip=20.2
  - pip:
      - azureml-defaults
      - azureml-designer-classic-modules==0.0.153
      - azureml-designer-serving==0.0.10
